services:
    website-testing:
        build:
            dockerfile: Dockerfile
            context: .
        image: php:7.4-apache
        working_dir: /var/www/html
        volumes:
            - './website/:/var/www/html'
        ports:
            - '80:8001'
        command: "php -S 0.0.0.0:8001"
